#Test Generated by ChatGPT
#Fibonacci Series.

.globl _start

_start:

# base address for storing fibonacci numbers
addi x10, x0, 128      # x10 = memory pointer

# n = 10
addi x11, x0, 10

# fib0 = 0
addi x12, x0, 0

# fib1 = 1
addi x13, x0, 1

# store first value
sw   x12, 0(x10)

# store second value
sw   x13, 4(x10)

# i = 2
addi x14, x0, 2

loop:

# if i >= n exit
bge  x14, x11, done

# fib_next = fib0 + fib1
add  x15, x12, x13

# store result
sw   x15, 0(x10)

# move window
add  x12, x13, x0
add  x13, x15, x0

# advance memory pointer
addi x10, x10, 4

# i++
addi x14, x14, 1

# jump back to loop
jal  x0, loop

done:

# infinite loop
jal x0, done